# Generated by Django 5.0.2 on 2024-03-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_DB',
            fields=[
                ('bookno', models.IntegerField(primary_key=True, serialize=False)),
                ('authorname', models.CharField(max_length=20)),
                ('bookname', models.CharField(max_length=50)),
                ('version', models.IntegerField()),
                ('pageno', models.IntegerField()),
            ],
        ),
    ]
